name: "Python Runner"
version: "1.0"
slug: "python_runner"
description: "Custom Python 3 environment for running scripts"
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
startup: "application"
boot: "auto"
ports:
  22223/tcp: 22223  # Custom SSH port
map:
  - config:rw  # Mounts /config
image: "python:3.11-slim"
init: false
options:
  password: "dreamBIG2025!@"
schema:
  password: str
